export const dummy_data = [
  {
    id: 1,
    name: "Reina Kathryne",
    role: "Manager",
    status: true,
    promote: true,
    rating: 3.0,
    date_login: "17-Nov-2023",
    profile_url: "http://dummyimage.com/128x106.png/ff4444/ffffff",
    checked: false,
  },
  {
    id: 2,
    name: "Geneva Doe",
    role: "Engineer",
    status: true,
    promote: false,
    rating: 0.7,
    date_login: "31-Mar-2024",
    profile_url: "http://dummyimage.com/145x113.png/5fa2dd/ffffff",
    checked: false,
  },
  {
    id: 3,
    name: "Page Kathryne",
    role: "Manager",
    status: true,
    promote: false,
    rating: 3.2,
    date_login: "09-Feb-2024",
    profile_url: "http://dummyimage.com/121x145.png/5fa2dd/ffffff",
    checked: true,
  },
  {
    id: 4,
    name: "Liesa Kathryne",
    role: "Engineer",
    status: false,
    promote: false,
    rating: 1.4,
    date_login: "09-Dec-2023",
    profile_url: "http://dummyimage.com/120x113.png/dddddd/000000",
    checked: false,
  },

  {
    id: 5,
    name: "Janean Kathryne ",
    role: "Engineer",
    status: true,
    promote: true,
    rating: 3.5,
    date_login: "08-Oct-2024",
    profile_url: "http://dummyimage.com/134x141.png/5fa2dd/ffffff",
    checked: false,
  },
  {
    id: 6,
    name: "Bidget Kathryne",
    role: "Engineer",
    status: true,
    promote: false,
    rating: 4.2,
    date_login: "19-Jan-2024",
    profile_url: "http://dummyimage.com/141x109.png/5fa2dd/ffffff",
    checked: false,
  },
  {
    id: 7,
    name: "Lay Kathryne",
    role: "Estimator",
    status: false,
    promote: true,
    rating: 1.2,
    date_login: "02-Jun-2024",
    profile_url: "http://dummyimage.com/102x134.png/5fa2dd/ffffff",
    checked: false,
  },
  {
    id: 8,
    name: "Rodolfo Kathryne",
    role: "Estimator",
    status: true,
    promote: false,
    rating: 3.5,
    date_login: "15-Nov-2023",
    profile_url: "http://dummyimage.com/127x148.png/5fa2dd/ffffff",
    checked: false,
  },
  {
    id: 9,
    name: "Kathryne Kathryne",
    role: "Manager",
    status: false,
    promote: false,
    rating: 2.8,
    date_login: "28-Aug-2024",
    profile_url: "http://dummyimage.com/135x112.png/ff4444/ffffff",
    checked: false,
  },
  {
    id: 10,
    name: "Timothea Kathryne",
    role: "Estimator",
    status: false,
    promote: false,
    rating: 4.5,
    date_login: "02-Dec-2023",
    profile_url: "http://dummyimage.com/114x143.png/ff4444/ffffff",
    checked: false,
  },
];
